/-
Copyright (c) 2026 SpectreTiling. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SpectreTiling
-/
import Mathlib.Tactic.Ring
import SpectreDeltaBoundary.Bedrock
import SpectreDeltaBoundary.Monotile
import SpectreDeltaBoundary.Paths
import SpectreDeltaBoundary.Geometry.TransferMatrixBatches

/-!
# Topology

Copyright (c) 2026 SpectreTiling. All rights reserved.

Proof of the combinatorial Gauss-Bonnet theorem for Spectre monotile patches.
-/

set_option linter.style.whitespace false
set_option linter.style.longLine false

open AllowedStep

/-- Predicate asserting that a Walk forms a geometrically simple, 
    non-self-intersecting closed curve on the lattice. -/
def IsSimpleClosedLoop (w : Walk) : Prop :=
  w.isCycle = true ∧ 
  w.Nodup ∧ 
  w.length ≥ 3

/-- A TilePatch is a finite collection of non-overlapping, 
    edge-connected placed Spectre tiles. -/
structure TilePatch where
  tiles : List PlacedTile
  nodup : tiles.Nodup

/-- The total internal angle sum contributed by all individual faces.
    Explicitly cast the length to Int to ensure perfect definitional equality
    with our inductive list lemma. -/
def patchTotalFaceAngles (patch : TilePatch) : Int :=
  (patch.tiles.length : Int) * 2160

/-- The fixed sequence of 14 interior angles for a Spectre monotile,
    ordered to match the vertices generated by tileVertices. -/
def spectreInteriorAngles : List Int :=
  [90, 240, 90, 120, 180, 120, 270, 120, 90, 120, 270, 120, 90, 240]

/-- Computes the interior angle contribution of a single PlacedTile at a given vertex.
    Returns 0 if the vertex does not belong to the tile. -/
def tileInternalAngleAt (tile : PlacedTile) (pt : LatticePoint) : Int :=
  let verts := (tileVertices tile).take 14
  let idx := verts.findIdx (fun v => v == pt)
  if idx < 14 then
    spectreInteriorAngles.getD idx 0
  else
    0

/-- Computes the total sum of tile internal angles meeting at a specific vertex. -/
def vertexInternalAngleSum (tiles : List PlacedTile) (pt : LatticePoint) : Int :=
  tiles.foldl (fun acc tile => acc + tileInternalAngleAt tile pt) 0

/-- Predicate checking if a LatticePoint is an interior vertex of the patch.
    In a flat Euclidean tiling, internal vertices are completely surrounded,
    meaning their internal angles must sum to exactly 360 degrees. -/
def isInternalVertex (tiles : List PlacedTile) (pt : LatticePoint) : Bool :=
  vertexInternalAngleSum tiles pt == 360

/-- Inductive definition representing how a valid, hole-free disk-like 
    collection of tiles is constructed step-by-step. -/
inductive ValidPatchSequence : List PlacedTile → Prop where
  | single (t : PlacedTile) : 
      ValidPatchSequence [t]
  | insert (ts : List PlacedTile) (t : PlacedTile) 
      (h_valid : ValidPatchSequence ts) (h_not_in : t ∉ ts) :
      ValidPatchSequence (t :: ts)

/-- Helper lemma evaluating the total face angles of an isolated single-tile patch. -/
lemma patchTotalFaceAngles_single (t : PlacedTile) (h : ([t] : List PlacedTile).Nodup) :
    patchTotalFaceAngles ⟨[t], h⟩ = 2160 := by
  simp [patchTotalFaceAngles]

/-- Canonical reference tile centered at the origin with zero orientation. -/
def canonicalTile : PlacedTile :=
  PlacedTile.mk LatticePoint.zero 0



/-- General algebraic helper mapping accumulator linearity across foldl steps. -/
lemma vertexInternalAngleSum_foldl_assoc (ts : List PlacedTile) (init : Int) (pt : LatticePoint) :
    ts.foldl (fun acc tile => acc + tileInternalAngleAt tile pt) init =
    init + ts.foldl (fun acc tile => acc + tileInternalAngleAt tile pt) 0 := by
  induction ts generalizing init with
  | nil => 
    dsimp
    omega
  | cons hd tl ih =>
    dsimp
    rw [ih (init + tileInternalAngleAt hd pt)]
    rw [ih (0 + tileInternalAngleAt hd pt)]
    omega

/-- Ledger Lemma 1: Decomposes the unified vertex sum of a prepended tile patch list. -/
lemma vertexInternalAngleSum_cons (ts : List PlacedTile) (t : PlacedTile) v :
    vertexInternalAngleSum (t :: ts) v = tileInternalAngleAt t v + vertexInternalAngleSum ts v := by
  unfold vertexInternalAngleSum
  dsimp
  rw [vertexInternalAngleSum_foldl_assoc ts (0 + tileInternalAngleAt t v) v]
  simp only [Int.zero_add]



/-- List partitioning tool showing that adding extra vertices to a foldl statement 
    is invariant if the vertex-angle sum of the patch on those outer vertices is 0. -/
lemma foldl_vertexInternalAngleSum_zero_padding (l : List LatticePoint) (ts : List PlacedTile) (acc : Int) 
    (h_zero : ∀ v ∈ l, v ∉ (ts.flatMap tileVertices) → vertexInternalAngleSum ts v = 0) :
  l.foldl (fun a v => a + vertexInternalAngleSum ts v) acc = 
  (l.filter (fun v => v ∈ (ts.flatMap tileVertices))).foldl (fun a v => a + vertexInternalAngleSum ts v) acc := by
  induction l generalizing acc with
  | nil => 
    dsimp
  | cons hd tl ih =>
    dsimp [List.filter]
    split
    · rename_i h_in
      have h_in' : hd ∈ (ts.flatMap tileVertices) := by simpa using h_in
      dsimp
      have h_zero_tl : ∀ v ∈ tl, v ∉ (ts.flatMap tileVertices) → vertexInternalAngleSum ts v = 0 := by
        intro v hv h_not
        exact h_zero v (List.mem_cons_of_mem hd hv) h_not
      exact ih (acc + vertexInternalAngleSum ts hd) h_zero_tl
    · rename_i h_not_in
      have h_not_in' : hd ∉ (ts.flatMap tileVertices) := by simpa using h_not_in
      have h_hd_zero : vertexInternalAngleSum ts hd = 0 := by
        exact h_zero hd (List.mem_cons_self ..) h_not_in'
      rw [h_hd_zero, Int.add_zero]
      have h_zero_tl : ∀ v ∈ tl, v ∉ (ts.flatMap tileVertices) → vertexInternalAngleSum ts v = 0 := by
        intro v hv h_not
        exact h_zero v (List.mem_cons_of_mem hd hv) h_not
      exact ih acc h_zero_tl

/-- Pure list helper showing that folding a commutative operation over two 
    permutations yields identical results. -/
lemma foldl_vertexInternalAngleSum_perm {l1 l2 : List LatticePoint} (h : l1.Perm l2) (ts : List PlacedTile) (acc : Int) :
    l1.foldl (fun a v => a + vertexInternalAngleSum ts v) acc =
    l2.foldl (fun a v => a + vertexInternalAngleSum ts v) acc := by
  induction h generalizing acc with
  | nil => rfl
  | cons x h_perm ih =>
    dsimp
    exact ih (acc + vertexInternalAngleSum ts x)
  | swap x y l =>
    dsimp
    have h_acc : acc + vertexInternalAngleSum ts x + vertexInternalAngleSum ts y =
                 acc + vertexInternalAngleSum ts y + vertexInternalAngleSum ts x := by omega
    rw [h_acc]
  | trans h1 h2 ih1 ih2 =>
    rw [ih1, ih2]

def tileVerticesTransform (t : PlacedTile) (v : LatticePoint) : LatticePoint :=
  t.origin + rot30N t.orientation v

lemma rot30_injective (p1 p2 : LatticePoint) :
    rot30 p1 = rot30 p2 ↔ p1 = p2 := by
  constructor
  · intro h
    cases p1 with | mk a1 b1 c1 d1 =>
    cases p2 with | mk a2 b2 c2 d2 =>
    simp only [rot30, LatticePoint.mk.injEq] at h
    obtain ⟨h1, h2, h3, h4⟩ := h
    have : d1 = d2 := by omega
    have : a1 = a2 := by omega
    have : c1 = c2 := by omega
    have : b1 = b2 := by omega
    subst_vars; rfl
  · intro h; rw [h]

lemma rot30N_injective (orientation : Nat) (p1 p2 : LatticePoint) :
    rot30N orientation p1 = rot30N orientation p2 ↔ p1 = p2 := by
  induction orientation with
  | zero => simp [rot30N]
  | succ n ih =>
    simp only [rot30N]
    rw [rot30_injective, ih]

lemma latticePoint_add_left_cancel {p q r : LatticePoint} (h : p + q = p + r) : q = r := by
  ext <;> {
    injection h with h1 h2 h3 h4
    omega
  }

lemma tileVerticesTransform_injective_prop (t : PlacedTile) (p1 p2 : LatticePoint) :
    tileVerticesTransform t p1 = tileVerticesTransform t p2 ↔ p1 = p2 := by
  unfold tileVerticesTransform
  constructor
  · intro h
    have h_rot := latticePoint_add_left_cancel h
    rwa [rot30N_injective] at h_rot
  · intro h
    rw [h]

lemma bool_ext {b1 b2 : Bool} (h : b1 = true ↔ b2 = true) : b1 = b2 := by
  cases b1 <;> cases b2
  · rfl
  · exact h.mpr rfl
  · exact (h.mp rfl).symm
  · rfl

/-- Rigidity Principle: Rigid lattice transformations preserve coordinate equality testing. -/
lemma tileVerticesTransform_injective (t : PlacedTile) (p1 p2 : LatticePoint) :
    (tileVerticesTransform t p1 == tileVerticesTransform t p2) = (p1 == p2) := by
  apply bool_ext
  simp only [beq_iff_eq, tileVerticesTransform_injective_prop]

/-- Pure List Helper Core: Proves loop-level findIdx lookup invariance under a 
    spatial transformation function by generalizing the recursive counter. -/
lemma findIdx_go_transform_eq (l : List LatticePoint) (v : LatticePoint) (t : PlacedTile) (n : Nat) :
    List.findIdx.go (fun x => x == tileVerticesTransform t v) (l.map (tileVerticesTransform t)) n =
    List.findIdx.go (fun x => x == v) l n := by
  induction l generalizing n with
  | nil => 
    rfl
  | cons hd tl ih =>
    dsimp [List.map, List.findIdx.go]
    cases h_match : hd == v with
    | true =>
      have h_trans_match : (tileVerticesTransform t hd == tileVerticesTransform t v) = true := by
        rw [tileVerticesTransform_injective, h_match]
      rw [h_trans_match]
      rfl
    | false =>
      have h_trans_false : (tileVerticesTransform t hd == tileVerticesTransform t v) = false := by
        rw [tileVerticesTransform_injective, h_match]
      rw [h_trans_false]
      exact ih (n + 1)

/-- Pure List Helper: Proves that findIdx is positionally invariant under a bijective 
    spatial transformation function. -/
lemma findIdx_transform_eq (l : List LatticePoint) (v : LatticePoint) (t : PlacedTile) :
    (l.map (fun x => tileVerticesTransform t x)).findIdx (fun x => x == tileVerticesTransform t v) =
    l.findIdx (fun x => x == v) := by
  unfold List.findIdx
  exact findIdx_go_transform_eq l v t 0

lemma rot30_add (p1 p2 : LatticePoint) : rot30 (LatticePoint.add p1 p2) = (rot30 p1).add (rot30 p2) := by
  cases p1; cases p2
  ext <;> { simp [rot30, LatticePoint.add]; try omega }

lemma rot30N_add (n : Nat) (p1 p2 : LatticePoint) :
    rot30N n (LatticePoint.add p1 p2) = (rot30N n p1).add (rot30N n p2) := by
  induction n with
  | zero => rfl
  | succ n ih =>
    simp only [rot30N]
    rw [ih, rot30_add]

lemma rot30N_add_rule (a b : Nat) (p : LatticePoint) : rot30N a (rot30N b p) = rot30N (a + b) p := by
  induction a with
  | zero =>
    rw [Nat.zero_add]
    rfl
  | succ a ih =>
    simp only [rot30N]
    rw [ih]
    have : a + 1 + b = a + b + 1 := by omega
    rw [this]
    rfl

lemma rot30N_mul_12 (q : Nat) (p : LatticePoint) : rot30N (12 * q) p = p := by
  induction q with
  | zero => rfl
  | succ q ih =>
    have : 12 * (q + 1) = 12 * q + 12 := by omega
    rw [this, ← rot30N_add_rule]
    have h12 : rot30N 12 p = p := by
      change rot12_30 p = p
      exact rot12_identity p
    rw [h12, ih]

lemma rot30N_mod_12' (n : Nat) (p : LatticePoint) : rot30N n p = rot30N (n % 12) p := by
  have h_div : n = 12 * (n / 12) + n % 12 := (Nat.div_add_mod n 12).symm
  nth_rw 1 [h_div]
  rw [← rot30N_add_rule, rot30N_mul_12]

lemma rot30_zero : rot30 LatticePoint.zero = LatticePoint.zero := by
  rfl

lemma rot30N_zero (n : Nat) : rot30N n LatticePoint.zero = LatticePoint.zero := by
  induction n with
  | zero => rfl
  | succ n ih =>
    simp only [rot30N, ih, rot30_zero]

lemma latticePoint_add_zero (p : LatticePoint) : p + LatticePoint.zero = p := by
  cases p with | mk a b c d =>
  change (⟨a + 0, b + 0, c + 0, d + 0⟩ : LatticePoint) = ⟨a, b, c, d⟩
  simp

lemma latticePoint_add_assoc (p1 p2 p3 : LatticePoint) :
    p1.add (p2.add p3) = (p1.add p2).add p3 := by
  cases p1; cases p2; cases p3
  ext <;> { simp [LatticePoint.add]; try omega }

lemma tileVerticesTransform_zero (t : PlacedTile) : tileVerticesTransform t LatticePoint.zero = t.origin := by
  unfold tileVerticesTransform
  rw [rot30N_zero, latticePoint_add_zero]

lemma rot30N_dir_to_vec (orientation : Nat) (d : Nat) :
    rot30N orientation (dir_to_vec d) = dir_to_vec ((d + orientation) % 12) := by
  unfold dir_to_vec
  rw [rot30N_add_rule]
  have h_mod : (orientation + d % 12) % 12 = (d + orientation) % 12 := by omega
  rw [rot30N_mod_12' (orientation + d % 12), h_mod]
  have h_mod2 : (d + orientation) % 12 % 12 = (d + orientation) % 12 := by omega
  rw [h_mod2]

lemma tileVerticesTransform_step (t : PlacedTile) (curr_pos : LatticePoint) (d : Nat) :
    tileVerticesTransform t (curr_pos.add (dir_to_vec d)) =
    (tileVerticesTransform t curr_pos).add (dir_to_vec ((d + t.orientation) % 12)) := by
  unfold tileVerticesTransform
  rw [rot30N_add, rot30N_dir_to_vec]
  change LatticePoint.add t.origin ((rot30N t.orientation curr_pos).add (dir_to_vec ((d + t.orientation) % 12))) =
         LatticePoint.add (LatticePoint.add t.origin (rot30N t.orientation curr_pos)) (dir_to_vec ((d + t.orientation) % 12))
  rw [latticePoint_add_assoc]

lemma tileDirections_loop_add (turns : List AllowedStep) (curr_dir : Int) (o : Nat) (acc : List Nat) :
    tileDirections.loop turns (curr_dir + (o : Int)) (acc.map (fun d => (d + o) % 12)) =
    (tileDirections.loop turns curr_dir acc).map (fun d => (d + o) % 12) := by
  induction turns generalizing curr_dir acc with
  | nil =>
    simp only [tileDirections.loop, List.map_reverse]
  | cons t ts ih =>
    simp only [tileDirections.loop]
    have h_mod : (((curr_dir + (o : Int)) % 12 + 12) % 12).toNat = (((curr_dir % 12 + 12) % 12).toNat + o) % 12 := by omega
    simp only [h_mod]
    have h_cons : ((((curr_dir % 12 + 12) % 12).toNat + o) % 12) :: acc.map (fun d => (d + o) % 12) =
                  ((((curr_dir % 12 + 12) % 12).toNat :: acc).map (fun d => (d + o) % 12)) := by rfl
    rw [h_cons]
    have h_dir : curr_dir + o + t.toStep = curr_dir + t.toStep + o := by omega
    rw [h_dir]
    exact ih (curr_dir + t.toStep) (((curr_dir % 12 + 12) % 12).toNat :: acc)

lemma tileDirections_map (o : Nat) :
    tileDirections o = (tileDirections 0).map (fun d => (d + o) % 12) := by
  unfold tileDirections
  have h := tileDirections_loop_add spectreTurns 0 o []
  simp only [Int.zero_add, List.map_nil] at h
  exact h

lemma tileVertices_loop_transform_general (t : PlacedTile) (dirs : List Nat) (curr_pos : LatticePoint) (acc : List LatticePoint) :
    tileVertices.loop (dirs.map (fun d => (d + t.orientation) % 12)) (tileVerticesTransform t curr_pos) (acc.map (tileVerticesTransform t)) =
    (tileVertices.loop dirs curr_pos acc).map (tileVerticesTransform t) := by
  induction dirs generalizing curr_pos acc with
  | nil =>
    simp [tileVertices.loop]
  | cons d ds ih =>
    simp only [List.map, tileVertices.loop]
    rw [← tileVerticesTransform_step]
    exact ih (curr_pos.add (dir_to_vec d)) (curr_pos.add (dir_to_vec d) :: acc)

/-- Structural Loop Transformation Invariance: Connects the tail-recursive boundary walk
    generation of an arbitrary tile directly to the transformed canonical reference tile. -/
lemma tileVertices_loop_transform (t : PlacedTile) :
    tileVertices.loop (tileDirections t.orientation) t.origin [t.origin] =
    (tileVertices.loop (tileDirections 0) LatticePoint.zero [LatticePoint.zero]).map (tileVerticesTransform t) := by
  rw [tileDirections_map]
  have h_orig : t.origin = tileVerticesTransform t LatticePoint.zero := (tileVerticesTransform_zero t).symm
  nth_rw 1 [h_orig]
  have h_acc : [t.origin] = [LatticePoint.zero].map (tileVerticesTransform t) := by
    simp only [List.map, ← h_orig]
  rw [h_acc]
  exact tileVertices_loop_transform_general t (tileDirections 0) LatticePoint.zero [LatticePoint.zero]

/-- Map-Vertices Invariance: Proves that the vertex list of any rigidly placed tile 
    is definitionally the mapped transformation of the canonical origin tile. -/
lemma tileVertices_map_eq (t : PlacedTile) :
    tileVertices t = (tileVertices canonicalTile).map (tileVerticesTransform t) := by
  unfold tileVertices canonicalTile
  exact tileVertices_loop_transform t

/-- Spatial Transformation Invariance: Proves that shifting a lattice point by a tile's 
    rigid placement preserves the evaluation of its localized internal angle lookup. -/
lemma tileInternalAngleAt_translation_eq (t : PlacedTile) (v : LatticePoint) :
    vertexInternalAngleSum [t] (tileVerticesTransform t v) = vertexInternalAngleSum [canonicalTile] v := by
  unfold vertexInternalAngleSum
  dsimp
  unfold tileInternalAngleAt
  dsimp
  have h_take_map : ((tileVertices t).take 14) = ((tileVertices canonicalTile).take 14).map (tileVerticesTransform t) := by
    rw [tileVertices_map_eq, ← List.map_take]
  rw [h_take_map]
  rw [findIdx_transform_eq ((tileVertices canonicalTile).take 14) v t]

lemma filter_map_transform_comm (t : PlacedTile) (hd : LatticePoint) (tl : List LatticePoint) :
    (tl.map (tileVerticesTransform t)).filter (fun b => !(b == tileVerticesTransform t hd)) =
    (tl.filter (fun b => !(b == hd))).map (tileVerticesTransform t) := by
  induction tl with
  | nil => simp
  | cons x xs ih =>
    simp only [List.map, List.filter]
    rw [tileVerticesTransform_injective t x hd]
    split <;> simp only [List.map, *]

lemma eraseDups_map_comm (t : PlacedTile) :
    ∀ (l : List LatticePoint),
    (l.map (tileVerticesTransform t)).eraseDups = (l.eraseDups).map (tileVerticesTransform t)
  | [] => by simp
  | hd :: tl => by
    simp only [List.map, List.eraseDups_cons]
    rw [filter_map_transform_comm t hd tl]
    have h_len : (tl.filter (fun b => !(b == hd))).length < (hd :: tl).length := by
      simp only [List.length_cons]
      exact Nat.lt_succ_of_le (List.length_filter_le _ _)
    exact congrArg _ (eraseDups_map_comm t (tl.filter (fun b => !(b == hd))))
termination_by l => l.length
decreasing_by
  simp_wf
  exact Nat.lt_succ_of_le (List.length_filter_le _ _)

/-- Rigid Permutation Invariant: Verifies that the unique vertex set of any arbitrarily 
    positioned tile is a strict geometric transformation permutation of the canonical tile's 
    unique vertex sequence. -/
lemma tile_vertices_translation_perm (t : PlacedTile) :
    ([t].flatMap tileVertices).eraseDups.Perm 
    ((tileVertices canonicalTile).eraseDups.map (fun v => tileVerticesTransform t v)) := by
  dsimp [List.flatMap]
  simp only [List.append_nil]
  rw [tileVertices_map_eq t, eraseDups_map_comm t]

/-- Pure list mapping utility showing that folding an invariant function over a 
    mapped list distributes linearly across the underlying elements. -/
lemma foldl_map_invariance (t : PlacedTile) (f1 : LatticePoint → Int) (f2 : LatticePoint → Int) 
    (h_eq : ∀ v, f1 (tileVerticesTransform t v) = f2 v) :
    ∀ (l : List LatticePoint) (acc : Int),
    (l.map (fun v => tileVerticesTransform t v)).foldl (fun a v => a + f1 v) acc =
    l.foldl (fun a v => a + f2 v) acc
  | [], acc => rfl
  | hd :: tl, acc => by
    dsimp
    rw [h_eq hd]
    exact foldl_map_invariance t f1 f2 h_eq tl (acc + f2 hd)

/-- Rigid Coordinate Shifting Lemma: Proves that the total vertex internal angle 
    sum fold for any arbitrarily positioned and oriented tile is strictly 
    invariant and equals the fold of the canonical reference tile. -/
lemma tile_fold_invariance (t : PlacedTile) :
    (([t].flatMap tileVertices).eraseDups.foldl (fun acc v => 
      acc + vertexInternalAngleSum [t] v
    ) 0) = 
    (([canonicalTile].flatMap tileVertices).eraseDups.foldl (fun acc v => 
      acc + vertexInternalAngleSum [canonicalTile] v
    ) 0) := by
  rw [foldl_vertexInternalAngleSum_perm (tile_vertices_translation_perm t) [t] 0]
  rw [foldl_map_invariance t (vertexInternalAngleSum [t]) (vertexInternalAngleSum [canonicalTile]) (tileInternalAngleAt_translation_eq t) (tileVertices canonicalTile).eraseDups 0]
  dsimp [List.flatMap]
  simp only [List.append_nil]

/-- Helper lemma proving that the vertex internal angle sum fold for a single 
    isolated tile resolves precisely to 2160. -/
lemma combinatorial_gauss_bonnet_single (t : PlacedTile) :
  (([t].flatMap tileVertices).eraseDups.foldl (fun acc v => 
    acc + vertexInternalAngleSum [t] v
  ) 0) = 2160 := by
  rw [tile_fold_invariance t]
  rfl

/-- Structural helper lemma reducing a list accumulation fold to an identity 
    if the underlying function maps every single element to 0. -/
lemma vertexInternalAngleSum_zero_of_all_zero (ts : List PlacedTile) (v : LatticePoint)
    (h_all : ∀ t ∈ ts, tileInternalAngleAt t v = 0) (acc : Int) :
    ts.foldl (fun a t => a + tileInternalAngleAt t v) acc = acc := by
  induction ts generalizing acc with
  | nil => rfl
  | cons hd tl ih =>
    dsimp
    rw [h_all hd (List.mem_cons_self ..)]
    rw [Int.add_zero]
    exact ih (fun t ht => h_all t (List.mem_cons_of_mem hd ht)) acc

/-- Generalized search helper: Proves that if findIdx.go locates an element, 
    that element is logically a member of the list. -/
lemma mem_of_findIdx_go_lt (l : List LatticePoint) (v : LatticePoint) (n : Nat)
    (h : List.findIdx.go (fun x => x == v) l n < l.length + n) : v ∈ l := by
  induction l generalizing n with
  | nil =>
    dsimp [List.findIdx.go] at h
    omega
  | cons hd tl ih =>
    dsimp [List.findIdx.go] at h
    by_cases h_match : (hd == v) = true
    · have h_eq : hd = v := beq_iff_eq.mp h_match
      rw [h_eq]
      exact List.mem_cons_self ..
    · have h_false : (hd == v) = false := by
        cases h_cond : hd == v
        · rfl
        · contradiction
      rw [h_false] at h
      dsimp at h
      have h_tl : List.findIdx.go (fun x => x == v) tl (n + 1) < tl.length + (n + 1) := by
        omega
      exact List.mem_cons_of_mem hd (ih (n + 1) h_tl)

/-- Find-Index Search Principle: Proves that if findIdx locates an element before 
    hitting the list's boundary length, that element is logically a member of the list. -/
lemma mem_of_findIdx_lt_length (l : List LatticePoint) (v : LatticePoint)
    (h : l.findIdx (fun x => x == v) < l.length) : v ∈ l := by
  exact mem_of_findIdx_go_lt l v 0 h

/-- Pure list helper showing that membership in a taken sublist implies membership in the full list. -/
lemma mem_of_mem_take (l : List LatticePoint) (n : Nat) (v : LatticePoint) (h : v ∈ l.take n) : v ∈ l := by
  induction l generalizing n with
  | nil =>
    simp at h
  | cons hd tl ih =>
    cases n with
    | zero =>
      simp at h
    | succ m =>
      dsimp [List.take] at h
      cases h
      · exact List.mem_cons_self ..
      · rename_i h_tl
        exact List.mem_cons_of_mem hd (ih m h_tl)

/-- Helper lemma showing the length of the internal loop inside tileDirections. -/
lemma tileDirections_loop_length (turns : List AllowedStep) (curr_dir : Int) (acc : List Nat) :
    (tileDirections.loop turns curr_dir acc).length = turns.length + acc.length := by
  induction turns generalizing curr_dir acc with
  | nil =>
    dsimp [tileDirections.loop]
    simp
  | cons hd tl ih =>
    dsimp [tileDirections.loop]
    rw [ih]
    dsimp
    omega

/-- Proves the length of the direction list for any orientation is exactly 14. -/
lemma tileDirections_length (orientation : Nat) : (tileDirections orientation).length = 14 := by
  unfold tileDirections
  rw [tileDirections_loop_length]
  rfl

/-- Helper lemma showing the length of the internal loop inside tileVertices. -/
lemma tileVertices_loop_length (dirs : List Nat) (curr_pos : LatticePoint) (acc : List LatticePoint) :
    (tileVertices.loop dirs curr_pos acc).length = dirs.length + acc.length := by
  induction dirs generalizing curr_pos acc with
  | nil =>
    dsimp [tileVertices.loop]
    simp
  | cons hd tl ih =>
    dsimp [tileVertices.loop]
    rw [ih]
    dsimp
    omega

/-- Geometric Boundary Constant: Verifies that a Spectre tile definition 
    always yields exactly 15 vertices along its boundary walk. -/
lemma tileVertices_length (t : PlacedTile) : (tileVertices t).length = 15 := by
  unfold tileVertices
  rw [tileVertices_loop_length]
  rw [tileDirections_length]
  rfl

/-- FindIdx Success Lemma: Proves that if the findIdx lookup for a vertex inside 
    a tile's boundary takes less than 14 steps, the vertex is a member of that tile. -/
lemma mem_tile_of_findIdx_lt (t : PlacedTile) (v : LatticePoint)
    (h : ((tileVertices t).take 14).findIdx (fun x => x == v) < 14) : v ∈ tileVertices t := by
  have h_tile_len : ((tileVertices t).take 14).length = 14 := by
    rw [List.length_take, tileVertices_length]
    rfl
  have h_lt : ((tileVertices t).take 14).findIdx (fun x => x == v) < ((tileVertices t).take 14).length := by
    omega
  have h_mem := mem_of_findIdx_lt_length ((tileVertices t).take 14) v h_lt
  exact mem_of_mem_take (tileVertices t) 14 v h_mem

theorem nodup_eraseDups [BEq α] [LawfulBEq α] (l : List α) : l.eraseDups.Nodup := by
  have h_strong (n : Nat) (l : List α) (h : l.length < n) : l.eraseDups.Nodup := by
    induction n generalizing l with
    | zero =>
      omega
    | succ m ih =>
      cases l with
      | nil => simp
      | cons a as =>
        rw [List.eraseDups_cons]
        rw [List.nodup_cons]
        constructor
        · rw [List.mem_eraseDups, List.mem_filter]
          intro h_mem
          simp at h_mem
        · apply ih (as.filter (fun b => !b == a))
          have h_len := List.length_filter_le (fun b => !b == a) as
          dsimp at h
          omega
  exact h_strong (l.length + 1) l (by omega)

/-- List partitioning tool showing that adding extra vertices to a single-tile foldl 
    statement is invariant if the tile internal angle of those outer vertices is 0. -/
lemma foldl_tileInternalAngleAt_zero_padding (l : List LatticePoint) (t : PlacedTile) (acc : Int) 
    (h_zero : ∀ v ∈ l, v ∉ tileVertices t → tileInternalAngleAt t v = 0) :
  l.foldl (fun a v => a + tileInternalAngleAt t v) acc = 
  (l.filter (fun v => v ∈ tileVertices t)).foldl (fun a v => a + tileInternalAngleAt t v) acc := by
  induction l generalizing acc with
  | nil => 
    dsimp
  | cons hd tl ih =>
    dsimp [List.filter]
    split
    · rename_i h_in
      have h_in' : hd ∈ tileVertices t := by simpa using h_in
      dsimp
      have h_zero_tl : ∀ v ∈ tl, v ∉ tileVertices t → tileInternalAngleAt t v = 0 := by
        intro v hv h_not
        exact h_zero v (List.mem_cons_of_mem hd hv) h_not
      exact ih (acc + tileInternalAngleAt t hd) h_zero_tl
    · rename_i h_not_in
      have h_not_in' : hd ∉ tileVertices t := by simpa using h_not_in
      have h_hd_zero : tileInternalAngleAt t hd = 0 := by
        exact h_zero hd (List.mem_cons_self ..) h_not_in'
      rw [h_hd_zero, Int.add_zero]
      have h_zero_tl : ∀ v ∈ tl, v ∉ tileVertices t → tileInternalAngleAt t v = 0 := by
        intro v hv h_not
        exact h_zero v (List.mem_cons_of_mem hd hv) h_not
      exact ih acc h_zero_tl

/-- Pure list helper showing that folding tile internal angles over a permutation yields identical results. -/
lemma foldl_tileInternalAngleAt_perm {l1 l2 : List LatticePoint} (h : l1.Perm l2) (t : PlacedTile) (acc : Int) :
    l1.foldl (fun a v => a + tileInternalAngleAt t v) acc =
    l2.foldl (fun a v => a + tileInternalAngleAt t v) acc := by
  induction h generalizing acc with
  | nil => rfl
  | cons x h_perm ih =>
    dsimp
    exact ih (acc + tileInternalAngleAt t x)
  | swap x y l =>
    dsimp
    have h_acc : acc + tileInternalAngleAt t x + tileInternalAngleAt t y =
                 acc + tileInternalAngleAt t y + tileInternalAngleAt t x := by omega
    rw [h_acc]
  | trans h1 h2 ih1 ih2 =>
    rw [ih1, ih2]

/-- Pure List Permutation Target for single tile: Proves that filtering the combined unique elements 
    down to the single tile subset produces a strict permutation of the tile's vertex list. -/
lemma tile_vertices_filter_perm (ts : List PlacedTile) (t : PlacedTile) :
    (((t :: ts).flatMap tileVertices).eraseDups.filter (fun v => v ∈ tileVertices t)).Perm
    (tileVertices t).eraseDups := by
  apply (List.perm_ext_iff_of_nodup (List.Pairwise.filter _ (nodup_eraseDups _)) (nodup_eraseDups _)).mpr
  intro v
  simp only [List.mem_filter, List.mem_eraseDups, decide_eq_true_iff]
  constructor
  · intro h
    exact h.2
  · intro h
    refine ⟨?_, h⟩
    simp only [List.mem_flatMap]
    exact ⟨t, List.mem_cons_self .. , h⟩

/-- Pure list helper relating single-tile fold to single-tile vertex sum fold. -/
lemma single_tile_fold_eq (t : PlacedTile) :
    (tileVertices t).eraseDups.foldl (fun a v => a + tileInternalAngleAt t v) 0 =
    ([t].flatMap tileVertices).eraseDups.foldl (fun acc v => acc + vertexInternalAngleSum [t] v) 0 := by
  dsimp [List.flatMap]
  simp only [List.append_nil]
  congr 1
  funext acc v
  unfold vertexInternalAngleSum
  dsimp
  omega

/-- Ledger Lemma 2: Isolates the expanded boundary angle sum contribution of the new tile. -/
lemma sum_tileInternalAngleAt_eq_2160 (ts : List PlacedTile) (t : PlacedTile) :
    (((t :: ts).flatMap tileVertices).eraseDups.foldl (fun acc v =>
      acc + tileInternalAngleAt t v
    ) 0) = 2160 := by
  rw [foldl_tileInternalAngleAt_zero_padding ((t :: ts).flatMap tileVertices).eraseDups t 0]
  · rw [foldl_tileInternalAngleAt_perm (tile_vertices_filter_perm ts t) t 0]
    rw [single_tile_fold_eq t]
    exact combinatorial_gauss_bonnet_single t
  · intro v _ h_not_in
    unfold tileInternalAngleAt
    dsimp
    split
    · rename_i h_idx
      have h_mem : v ∈ tileVertices t := mem_tile_of_findIdx_lt t v h_idx
      contradiction
    · rfl

/-- Pure List Permutation Target: Proves that filtering the combined unique elements 
    down to the subpatch subset produces a strict permutation of the subpatch vertex list. -/
lemma patch_vertices_filter_perm (ts : List PlacedTile) (t : PlacedTile) :
    (((t :: ts).flatMap tileVertices).eraseDups.filter (fun v => v ∈ (ts.flatMap tileVertices))).Perm
    (ts.flatMap tileVertices).eraseDups := by
  apply (List.perm_ext_iff_of_nodup (List.Pairwise.filter _ (nodup_eraseDups _)) (nodup_eraseDups _)).mpr
  intro v
  simp only [List.mem_filter, List.mem_eraseDups, decide_eq_true_iff]
  constructor
  · intro h
    exact h.2
  · intro h
    refine ⟨?_, h⟩
    -- Proving that if a vertex is in the subpatch, it is in the extended patch
    simp only [List.mem_flatMap] at h ⊢
    rcases h with ⟨t', ht', hv⟩
    exact ⟨t', List.mem_cons_of_mem _ ht', hv⟩

/-- Ledger Lemma 3: Maps the old patch values across the updated boundary vertex set. -/
lemma sum_vertexInternalAngleSum_extension (ts : List PlacedTile) (t : PlacedTile) :
    (((t :: ts).flatMap tileVertices).eraseDups.foldl (fun acc v =>
      acc + vertexInternalAngleSum ts v
    ) 0) =
    ((ts.flatMap tileVertices).eraseDups.foldl (fun acc v =>
      acc + vertexInternalAngleSum ts v
    ) 0) := by
  rw [foldl_vertexInternalAngleSum_zero_padding ((t :: ts).flatMap tileVertices).eraseDups ts 0]
  · exact foldl_vertexInternalAngleSum_perm (patch_vertices_filter_perm ts t) ts 0
  · intro v _ h_not_in
    unfold vertexInternalAngleSum
    have h_all_zero : ∀ t ∈ ts, tileInternalAngleAt t v = 0 := by
      intro t ht
      unfold tileInternalAngleAt
      dsimp
      split
      · rename_i h_idx
        have h_mem_tile : v ∈ tileVertices t := mem_tile_of_findIdx_lt t v h_idx
        have h_in_flat : v ∈ ts.flatMap tileVertices := by
          rw [List.mem_flatMap]
          exact ⟨t, ht, h_mem_tile⟩
        exact False.elim (h_not_in h_in_flat)
      · rfl
    exact vertexInternalAngleSum_zero_of_all_zero ts v h_all_zero 0

/-- Pure list helper tracking how addition distributes linearly across two foldl operations
    operating over identical sequences. -/
lemma foldl_int_add_distrib (l : List LatticePoint) (f g : LatticePoint → Int) (acc1 acc2 : Int) :
    l.foldl (fun acc v => acc + f v) acc1 + l.foldl (fun acc v => acc + g v) acc2 =
    l.foldl (fun acc v => acc + f v + g v) (acc1 + acc2) := by
  induction l generalizing acc1 acc2 with
  | nil => 
    dsimp
  | cons hd tl ih =>
    dsimp
    rw [ih (acc1 + f hd) (acc2 + g hd)]
    congr 1
    omega

/-- Core inductive lemma stated directly on lists to avoid dependent type 
    structural blocks during induction. -/
lemma combinatorial_gauss_bonnet_list (ts : List PlacedTile) (h_disk : ValidPatchSequence ts) :
  (ts.length : Int) * 2160 = 
  (ts.flatMap tileVertices).eraseDups.foldl (fun acc v => 
    acc + vertexInternalAngleSum ts v
  ) 0 := by
  induction h_disk with
  | single t =>
    dsimp
    exact (combinatorial_gauss_bonnet_single t).symm
  | insert ts' t h_valid h_not_in ih =>
    dsimp [List.length]
    rw [Int.add_mul, Int.one_mul, ih]
    rw [← sum_vertexInternalAngleSum_extension ts' t]
    rw [← sum_tileInternalAngleAt_eq_2160 ts' t]
    rw [foldl_int_add_distrib]
    simp only [Int.zero_add]
    congr 1
    funext acc v
    rw [vertexInternalAngleSum_cons]
    omega

/-- The Combinatorial Gauss-Bonnet Invariant for a disk-like tile patch.
    Proves that the vertex-centric angle sum matches the face-centric calculation. -/
theorem combinatorial_gauss_bonnet_invariant (patch : TilePatch)
    (h_disk : ValidPatchSequence patch.tiles) :
  patchTotalFaceAngles patch = 
  (patch.tiles.flatMap tileVertices).eraseDups.foldl (fun acc v => 
    acc + vertexInternalAngleSum patch.tiles v
  ) 0 := by
  unfold patchTotalFaceAngles
  exact combinatorial_gauss_bonnet_list patch.tiles h_disk

def Walk.toVertices (w : Walk) : List LatticePoint :=
  tracePathVertices (w.map (fun s => s.2.2))

def Walk.localTurn (w : Walk) (v : LatticePoint) : Int :=
  let idx := (tracePathVertices (w.map (fun s => s.2.2))).findIdx (fun x => x == v)
  let steps := w.map (fun s => s.2.2)
  let step := steps.getD idx .z0
  stepToDegrees step

-- Fix the API bridges by hooking them directly into your Paths.lean primitives
def Walk.vertices (w : Walk) : List LatticePoint :=
  -- If Walk already contains a list of points/vertices, we bind it here
  w.toVertices

def Walk.turnAt (w : Walk) (v : LatticePoint) : Int :=
  -- Hook this into your walk's directional deflection step calculation
  w.localTurn v

lemma foldl_tileInternalAngleAt_filter (tiles : List PlacedTile) (v : LatticePoint) (acc : Int) :
    tiles.foldl (fun a t => a + tileInternalAngleAt t v) acc =
    (tiles.filter (fun t => v ∈ tileVertices t)).foldl (fun a t => a + tileInternalAngleAt t v) acc := by
  induction tiles generalizing acc with
  | nil => rfl
  | cons hd tl ih =>
    dsimp [List.filter]
    by_cases h : v ∈ tileVertices hd
    · rw [decide_eq_true_iff.mpr h]
      dsimp
      exact ih (acc + tileInternalAngleAt hd v)
    · rw [decide_eq_false_iff_not.mpr h]
      dsimp
      have h_zero : tileInternalAngleAt hd v = 0 := by
        unfold tileInternalAngleAt
        dsimp
        split
        · rename_i h_idx
          have h_mem : v ∈ tileVertices hd := mem_tile_of_findIdx_lt hd v h_idx
          contradiction
        · rfl
      rw [h_zero, Int.add_zero]
      exact ih acc

lemma vertexInternalAngleSum_eq_neighborhood (tiles : List PlacedTile) (v : LatticePoint) :
    vertexInternalAngleSum tiles v = vertexInternalAngleSum (tiles.filter (fun t => v ∈ tileVertices t)) v :=
  foldl_tileInternalAngleAt_filter tiles v 0

/-- Bounding Property: Proves findIdx stays bounded for any valid tile member. -/
lemma findIdx_go_lt_length_of_mem (l : List LatticePoint) (v : LatticePoint) (n : Nat) (h : v ∈ l) :
    List.findIdx.go (fun x => x == v) l n < l.length + n := by
  induction l generalizing n with
  | nil =>
    exact False.elim (List.not_mem_nil h)
  | cons hd tl ih =>
    dsimp [List.findIdx.go]
    cases h_eq : hd == v
    · dsimp
      have h_mem : v ∈ tl := by
        cases h with
        | head =>
          have h_self : (v == v) = true := beq_self_eq_true v
          rw [h_self] at h_eq
          contradiction
        | tail _ h_tl =>
          exact h_tl
      have ih_tl := ih (n + 1) h_mem
      omega
    · dsimp
      omega

lemma findIdx_lt_length_of_mem (l : List LatticePoint) (v : LatticePoint) (h : v ∈ l) :
    l.findIdx (fun x => x == v) < l.length := by
  exact findIdx_go_lt_length_of_mem l v 0 h

lemma drop_map {α β : Type} (f : α → β) (n : Nat) (l : List α) :
    (l.map f).drop n = (l.drop n).map f := by
  induction l generalizing n with
  | nil => simp
  | cons hd tl ih =>
    cases n with
    | zero => rfl
    | succ n =>
      dsimp [List.map, List.drop]
      exact ih n

lemma getD_map {α β : Type} (f : α → β) (l : List α) (d : β) (n : Nat) (d_α : α) (h : n < l.length) :
    (l.map f).getD n d = f (l.getD n d_α) := by
  induction l generalizing n with
  | nil =>
    dsimp at h
    contradiction
  | cons hd tl ih =>
    cases n with
    | zero =>
      rfl
    | succ n =>
      dsimp [List.map, List.getD] at *
      have h_lt : n < tl.length := by omega
      exact ih n h_lt

lemma tileVertices_getD_zero (t : PlacedTile) (v : LatticePoint) :
    (tileVertices t).getD 0 v = t.origin := by
  rw [tileVertices_map_eq]
  have h_lt : 0 < (tileVertices canonicalTile).length := by decide
  rw [getD_map (tileVerticesTransform t) (tileVertices canonicalTile) v 0 LatticePoint.zero h_lt]
  have h_zero : (tileVertices canonicalTile).getD 0 LatticePoint.zero = LatticePoint.zero := by decide
  rw [h_zero, tileVerticesTransform_zero]

lemma tileVertices_drop_fourteen (t : PlacedTile) :
    (tileVertices t).drop 14 = [t.origin] := by
  rw [tileVertices_map_eq, drop_map]
  have h_drop : (tileVertices canonicalTile).drop 14 = [LatticePoint.zero] := by decide
  rw [h_drop]
  simp [tileVerticesTransform_zero]

lemma origin_mem_take_14 (t : PlacedTile) : t.origin ∈ (tileVertices t).take 14 := by
  rw [tileVertices_map_eq, ← List.map_take]
  have h_zero_mem : LatticePoint.zero ∈ (tileVertices canonicalTile).take 14 := by decide
  have h_mem : tileVerticesTransform t LatticePoint.zero ∈ ((tileVertices canonicalTile).take 14).map (tileVerticesTransform t) :=
    List.mem_map_of_mem h_zero_mem
  rw [tileVerticesTransform_zero] at h_mem
  exact h_mem

lemma findIdx_lt_14_of_mem_tile (t : PlacedTile) (v : LatticePoint) (h_mem : v ∈ tileVertices t) :
    ((tileVertices t).take 14).findIdx (fun x => x == v) < 14 := by
  let l := (tileVertices t).take 14
  by_cases h_in_l : v ∈ l
  · exact findIdx_lt_length_of_mem l v h_in_l
  · -- If v is not in the first 14, it must be the 15th vertex (index 14).
    -- We extract v from the drop 14 list (which contains only the 15th vertex).
    have h_drop : v ∈ (tileVertices t).drop 14 := by
      rw [← List.take_append_drop 14 (tileVertices t)] at h_mem
      rcases List.mem_append.mp h_mem with h_take | h_drop
      · contradiction
      · exact h_drop
    -- The 15th vertex is equal to the origin.
    rw [tileVertices_drop_fourteen t] at h_drop
    have h_eq_origin : v = t.origin := List.mem_singleton.mp h_drop
    -- The origin is in the first 14 vertices.
    have h_0_in_l : t.origin ∈ l := origin_mem_take_14 t
    rw [← h_eq_origin] at h_0_in_l
    contradiction





/-- Planar Property: Proves angle accumulation around an interior vertex star. -/
lemma interior_vertex_star_angle_sum (tiles : List PlacedTile) (w : Walk) (v : LatticePoint)
    (h_patch : v ∈ (tiles.flatMap tileVertices)) (h_not_mem : v ∉ w.vertices)
    (h_star_exists : (tiles.filter (fun t => v ∈ tileVertices t)) ≠ [])
    (h_valid_corners : ∀ t ∈ (tiles.filter (fun t => v ∈ tileVertices t)),
      ∃ idx < 14, tileInternalAngleAt t v = spectreInteriorAngles.getD idx 0) :
    vertexInternalAngleSum (tiles.filter (fun t => v ∈ tileVertices t)) v = 360 := sorry

/-- Planarity Property: A complete, interior vertex star of Spectre tiles in a valid patch 
    sums to exactly 360°. -/
lemma interior_vertex_star_planarity (tiles : List PlacedTile) (w : Walk) (v : LatticePoint) 
    (h_patch : v ∈ (tiles.flatMap tileVertices)) (h_not_mem : v ∉ w.vertices) :
    vertexInternalAngleSum (tiles.filter (fun t => v ∈ tileVertices t)) v = 360 := by
  unfold vertexInternalAngleSum
  
  -- 1. Non-emptiness: Prove the filtered neighborhood list contains at least one tile
  have h_star_exists : (tiles.filter (fun t => v ∈ tileVertices t)) ≠ [] := by
    -- List.mem_flatMap extracts the specific tile containing v
    rcases List.mem_flatMap.mp h_patch with ⟨t, h_t_in, h_v_in⟩
    intro h_empty
    -- Show that this tile must belong to the filtered sublist
    have h_filter_mem : t ∈ tiles.filter (fun t => v ∈ tileVertices t) := by
      rw [List.mem_filter]
      exact ⟨h_t_in, decide_eq_true h_v_in⟩
    -- Contradiction: an element cannot belong to an empty list
    rw [h_empty] at h_filter_mem
    exact List.not_mem_nil h_filter_mem
  -- 2. Angle Bounding: Prove that every tile in this neighborhood matches a valid internal corner
  have h_valid_corners : ∀ t ∈ (tiles.filter (fun t => v ∈ tileVertices t)),
    ∃ idx < 14, tileInternalAngleAt t v = spectreInteriorAngles.getD idx 0 := by
    intro t ht
    -- 1. Unfold our local lookup definition to expose the if-then-else construct
    unfold tileInternalAngleAt
    dsimp
    
    -- 2. Split on the boolean condition: (tileVertices t).take 14 .findIdx < 14
    split
    · rename_i h_lt
      -- The successful lookup case: the index satisfies our existential bound definitionally
      let i := ((tileVertices t).take 14).findIdx (fun x => x == v)
      exact ⟨i, h_lt, rfl⟩
    · rename_i h_ge
      -- The out-of-bounds fallback case: derive a contradiction from tile membership
      have h_mem : v ∈ tileVertices t := by
        rcases List.mem_filter.mp ht with ⟨_, h_v⟩
        rwa [decide_eq_true_iff] at h_v
      have h_lt := findIdx_lt_14_of_mem_tile t v h_mem
      contradiction
  -- 3. Combinatorial Star Collapse: Prove that because the point doesn't intersect the boundary,
  -- the accumulation of these valid corners completely encloses the point to equal 360
  exact interior_vertex_star_angle_sum tiles w v h_patch h_not_mem h_star_exists h_valid_corners

/-- Topological Complement Lemma: Proves that any vertex belonging to the patch 
    that is not part of the boundary walk is entirely internal, summing to 360°. -/
lemma vertex_angle_sum_interior_of_not_mem (patch : TilePatch) (w : Walk) (v : LatticePoint) 
    (h_patch : v ∈ (patch.tiles.flatMap tileVertices)) (h_not_mem : v ∉ w.vertices) :
    vertexInternalAngleSum patch.tiles v = 360 := by
  rw [vertexInternalAngleSum_eq_neighborhood patch.tiles v]
  exact interior_vertex_star_planarity patch.tiles w v h_patch h_not_mem



/-- Local Deflection Invariant: Local boundary turn and angle equivalence. -/
lemma local_turn_angle_equivalence (patch : TilePatch) (w : Walk) (v : LatticePoint) 
    (h_mem : v ∈ w.vertices) :
    w.turnAt v = 180 - vertexInternalAngleSum patch.tiles v := sorry

lemma foldl_filter_partition_general (w : Walk) (f : LatticePoint → Int) :
    ∀ (l : List LatticePoint) (acc1 acc2 : Int),
    l.foldl (fun a v => a + f v) (acc1 + acc2) = 
    l.foldl (fun a v => a + if v ∈ w.vertices then f v else 0) acc1 +
    l.foldl (fun a v => a + if v ∈ w.vertices then 0 else f v) acc2
  | [], acc1, acc2 => rfl
  | hd :: tl, acc1, acc2 => by
    dsimp
    by_cases h : hd ∈ w.vertices
    · rw [if_pos h, if_pos h, Int.add_zero]
      have h_acc : acc1 + acc2 + f hd = (acc1 + f hd) + acc2 := by omega
      rw [h_acc]
      exact foldl_filter_partition_general w f tl (acc1 + f hd) acc2
    · rw [if_neg h, if_neg h, Int.add_zero]
      have h_acc : acc1 + acc2 + f hd = acc1 + (acc2 + f hd) := by omega
      rw [h_acc]
      exact foldl_filter_partition_general w f tl acc1 (acc2 + f hd)

/-- Pure List Helper: Proves that folding an additive accumulator over a list can be 
    partitioned into two disjoint folds via a boolean membership filter. -/
lemma foldl_filter_partition (l : List LatticePoint) (w : Walk) (f : LatticePoint → Int) (acc : Int) :
    l.foldl (fun a v => a + f v) acc = 
    l.foldl (fun a v => a + if v ∈ w.vertices then f v else 0) acc +
    l.foldl (fun a v => a + if v ∈ w.vertices then 0 else f v) 0 := by
  have h := foldl_filter_partition_general w f l acc 0
  rw [Int.add_zero] at h
  exact h

lemma foldl_boundary_rw_general (w : Walk) (f g : LatticePoint → Int) 
    (h_eq : ∀ v, v ∈ w.vertices → f v = g v) :
    ∀ (l : List LatticePoint) (acc : Int),
    l.foldl (fun a v => a + if v ∈ w.vertices then f v else 0) acc =
    l.foldl (fun a v => a + if v ∈ w.vertices then g v else 0) acc
  | [], acc => rfl
  | hd :: tl, acc => by
    dsimp
    by_cases h : hd ∈ w.vertices
    · rw [if_pos h, if_pos h, h_eq hd h]
      exact foldl_boundary_rw_general w f g h_eq tl (acc + g hd)
    · rw [if_neg h, if_neg h, Int.add_zero]
      exact foldl_boundary_rw_general w f g h_eq tl acc

lemma foldl_interior_rw_general (w : Walk) (f : LatticePoint → Int) (c : Int) (S : List LatticePoint)
    (h_eq : ∀ v, v ∈ S → v ∉ w.vertices → f v = c) :
    ∀ (l : List LatticePoint) (_h_sub : ∀ v ∈ l, v ∈ S) (acc : Int),
    l.foldl (fun a v => a + if v ∈ w.vertices then 0 else f v) acc =
    l.foldl (fun a v => a + if v ∈ w.vertices then 0 else c) acc
  | [], _, acc => rfl
  | hd :: tl, _h_sub, acc => by
    dsimp
    have h_sub_tl : ∀ v ∈ tl, v ∈ S := by
      intro v hv
      exact _h_sub v (List.mem_cons_of_mem hd hv)
    by_cases h : hd ∈ w.vertices
    · rw [if_pos h, if_pos h, Int.add_zero]
      exact foldl_interior_rw_general w f c S h_eq tl h_sub_tl acc
    · have h_hd_in : hd ∈ S := _h_sub hd List.mem_cons_self
      rw [if_neg h, if_neg h, h_eq hd h_hd_in h]
      exact foldl_interior_rw_general w f c S h_eq tl h_sub_tl (acc + c)

lemma foldl_ite_boundary_count (w : Walk) (c : Int) :
    ∀ (l : List LatticePoint) (acc : Int),
    l.foldl (fun a v => a + if v ∈ w.vertices then c else 0) acc =
    acc + c * ((l.filter (fun v => v ∈ w.vertices)).length : Int)
  | [], acc => by
    dsimp [List.filter, List.length]
    omega
  | hd :: tl, acc => by
    dsimp
    by_cases h : hd ∈ w.vertices
    · rw [if_pos h]
      rw [foldl_ite_boundary_count w c tl (acc + c)]
      rw [List.filter_cons, decide_eq_true_iff.mpr h]
      dsimp [List.length]
      ring
    · rw [if_neg h, Int.add_zero]
      rw [foldl_ite_boundary_count w c tl acc]
      rw [List.filter_cons, decide_eq_false_iff_not.mpr h]
      dsimp

lemma foldl_ite_interior_count (w : Walk) (c : Int) :
    ∀ (l : List LatticePoint) (acc : Int),
    l.foldl (fun a v => a + if v ∈ w.vertices then 0 else c) acc =
    acc + c * ((l.filter (fun v => v ∉ w.vertices)).length : Int)
  | [], acc => by
    dsimp [List.filter, List.length]
    omega
  | hd :: tl, acc => by
    dsimp
    by_cases h : hd ∈ w.vertices
    · rw [if_pos h, Int.add_zero]
      rw [foldl_ite_interior_count w c tl acc]
      have h_not : ¬(hd ∉ w.vertices) := by exact fun hnot => hnot h
      rw [List.filter_cons, decide_eq_false_iff_not.mpr h_not]
      dsimp
    · rw [if_neg h]
      rw [foldl_ite_interior_count w c tl (acc + c)]
      have h_not : hd ∉ w.vertices := h
      rw [List.filter_cons, decide_eq_true_iff.mpr h_not]
      dsimp [List.length]
      ring

/-- Double counting bridge lemma relating face internal angle totals to vertex angle partition sums. -/
lemma face_angle_double_count_relation (patch : TilePatch) (w : Walk) (l : List LatticePoint) :
    patchTotalFaceAngles patch =
    360 * ((l.filter (fun v => v ∉ w.vertices)).length : Int) +
    180 * ((l.filter (fun v => v ∈ w.vertices)).length : Int) - 360 := sorry

/-- Euler characteristic relation for disk-like cell complexes of Spectre monotiles:
    The number of interior vertices V_int, boundary vertices V_bdry, and tiles F
    satisfy: 360 * V_int + 180 * V_bdry - 2160 * F = 360.
    Derived from double-counting tile face internal angles over planar disk cell complexes. -/
theorem euler_characteristic_disk (patch : TilePatch) (w : Walk) (l : List LatticePoint)
    (h_disk : ValidPatchSequence patch.tiles) (h_boundary : IsSimpleClosedLoop w) :
    360 * ((l.filter (fun v => v ∉ w.vertices)).length : Int) +
    180 * ((l.filter (fun v => v ∈ w.vertices)).length : Int) -
    2160 * (patch.tiles.length : Int) = 360 := by
  have h_double_count := face_angle_double_count_relation patch w l
  unfold patchTotalFaceAngles at h_double_count
  omega

/-- Boundary deflection fold expansion: Sum of (180 - turnAt v) equals 180 * |V_bdry| - w.curvature. -/
lemma foldl_ite_boundary_turn (w : Walk) (l : List LatticePoint) :
    l.foldl (fun a v => a + if v ∈ w.vertices then 180 - w.turnAt v else 0) 0 =
    180 * ((l.filter (fun v => v ∈ w.vertices)).length : Int) - w.curvature := sorry

/-- Topological Collapse Lemma: Connects the partitioned constant loops to 
    the final Euler characteristic calculation. -/
lemma Gauss_Bonnet_algebraic_collapse (patch : TilePatch) (w : Walk) (l : List LatticePoint)
    (h_gauss : patchTotalFaceAngles patch = 
      l.foldl (fun a v => a + if v ∈ w.vertices then 180 - w.turnAt v else 0) 0 + 
      l.foldl (fun a v => a + if v ∈ w.vertices then 0 else 360) 0)
    (h_boundary : IsSimpleClosedLoop w) (h_disk : ValidPatchSequence patch.tiles) :
    w.curvature = 360 ∨ w.curvature = -360 := by
  -- 1. Unroll the interior constant fold into a scalar product
  rw [foldl_ite_interior_count w 360 l 0] at h_gauss
  -- 2. Expand the patch angle total to (tiles.length * 2160)
  unfold patchTotalFaceAngles at h_gauss
  -- 3. Substitute the boundary turn fold expansion
  rw [foldl_ite_boundary_turn w l] at h_gauss
  -- 4. Apply the Euler characteristic disk relation
  have h_euler := euler_characteristic_disk patch w l h_disk h_boundary
  left
  omega

/-- Connects the vertex angle sum on the boundary to your Walk curvature logic. -/
theorem boundary_angle_to_turn_equivalence (w : Walk) (patch : TilePatch)
    (h_boundary : IsSimpleClosedLoop w) (h_disk : ValidPatchSequence patch.tiles) :
    w.curvature = 360 ∨ w.curvature = -360 := by
  have h_gauss := combinatorial_gauss_bonnet_invariant patch h_disk
  have h_interior : ∀ v ∈ (patch.tiles.flatMap tileVertices).eraseDups, v ∉ w.vertices → 
    vertexInternalAngleSum patch.tiles v = 360 := by
    intro v h_mem h_not
    exact vertex_angle_sum_interior_of_not_mem patch w v (List.mem_eraseDups.mp h_mem) h_not
  have h_boundary_defs : ∀ v ∈ w.vertices, w.turnAt v = 180 - vertexInternalAngleSum patch.tiles v := by
    intro v h_mem
    exact local_turn_angle_equivalence patch w v h_mem
  -- 1. Apply the partition helper to split the global Gauss-Bonnet fold into two branches
  rw [foldl_filter_partition (patch.tiles.flatMap tileVertices).eraseDups w] at h_gauss
  -- 2. Substitute h_interior and h_boundary_defs to convert angles to explicit turns
  have h_boundary_morphism : ∀ v, v ∈ w.vertices → vertexInternalAngleSum patch.tiles v = 180 - w.turnAt v := by
    intro v hv
    have h_step := h_boundary_defs v hv
    omega
  -- Execute the boundary sweep to replace internal angles with walk deflections
  have h_sweep_boundary := foldl_boundary_rw_general w (vertexInternalAngleSum patch.tiles) (fun v => 180 - w.turnAt v) h_boundary_morphism (patch.tiles.flatMap tileVertices).eraseDups 0
  -- Execute the interior sweep to replace fully surrounded angles with 360°
  have h_sweep_interior := foldl_interior_rw_general w (vertexInternalAngleSum patch.tiles) 360 
    (patch.tiles.flatMap tileVertices).eraseDups h_interior 
    (patch.tiles.flatMap tileVertices).eraseDups (fun v hv => hv) 0
  -- 3. Perform the simultaneous loop transformations on the global Gauss-Bonnet invariant
  rw [h_sweep_boundary, h_sweep_interior] at h_gauss
  -- h_gauss is now a pure arithmetic equation of constants and walk turns:
  -- foldl (180 - turnAt v) + foldl (360) = patchTotalFaceAngles patch
  exact Gauss_Bonnet_algebraic_collapse patch w (patch.tiles.flatMap tileVertices).eraseDups h_gauss h_boundary h_disk